name: Nápad na zlepšení
description: Různé nové nápady, které mohu do aplikace, materiálů či na discord přidat.
title: "[NÁPAD] "
assignees: 
  - cajthamlmatej
body:
  - type: dropdown
    id: section
    attributes:
      label: V jaké aplikaci se nachází nápad?
      options:
        - Portál (webová stránka)
        - Hosting (circumrota)
        - Testovací API (morsmordre)
        - Discord
        - Materiály
        - ostatní
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Popis nápadu
      description: Zkuste svůj nápad jednoduše a přehledně sepsat, aby dával smysl. Popište i kde by se daná funkčnost nacházela.
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Zdůvodnění
      description: Zdůvodněte, proč by tato funkčnost byla vhodná a dobrá. Můžete určit i kdo a jak ji bude využívat.
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Vaše jméno
      description: Ze jména by mělo být jasné, kdo jste. Může být použito pro udělení bodů za aktivitu.
    validations:
      required: false
